# Default values for ipedworker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 192.168.2.191:5001/ipeddocker/worker-go
  tag: 2.3.8-3.15.6
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

env:
  - name: IPEDJAR
    value: /root/IPED/iped/iped.jar
  - name: LOCK_URL
    value: http://$(LOCKER_SERVICE_HOST):$(LOCKER_SERVICE_PORT)
  - name: NOTIFY_URL
    value: http://$(WEKAN_NOTIFIER_SERVICE_HOST):$(WEKAN_NOTIFIER_SERVICE_PORT)
  - name: WATCH_URL
    value: http://$(WEKAN_WATCHER_SERVICE_HOST):$(WEKAN_WATCHER_SERVICE_PORT)

volumeMounts:
  - mountPath: /mnt/ipedtmp
    name: ipedtmp
  - mountPath: /mnt/cloud/operacoes
    name: operacoes
  - mountPath: /operacoes
    name: operacoes
  - mountPath: /mnt/led
    name: led
  - mountPath: /mnt/kff
    name: kff
  - mountPath: /mnt/PhotoDNA
    name: photodna

volumes:
  - hostPath:
      path: /mnt/ipedtmp/
      type: Directory
    name: ipedtmp
  - cephfs:
      monitors:
      - 192.168.2.42:6789
      user: admin
      secretRef:
        name: ceph-secret
      path: /operacoes/
    name: operacoes
  - cephfs:
      monitors:
      - 192.168.2.42:6789
      user: admin
      secretRef:
        name: ceph-secret
      path: /led/V1.25.01
    name: led
  - cephfs:
      monitors:
      - 192.168.2.42:6789
      user: admin
      secretRef:
        name: ceph-secret
      path: /kff/iped-kff-1.2
    name: kff
  - cephfs:
      monitors:
      - 192.168.2.42:6789
      user: admin
      secretRef:
        name: ceph-secret
      path: /PhotoDNA
    name: photodna


ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 16
    memory: 64Gi
  requests:
    cpu: 16
    memory: 64Gi

nodeSelector: {}

tolerations: []

affinity: {}
